allowBuilds:
  "@parcel/watcher": false
  "@tailwindcss/oxide": false
  better-sqlite3: true
  esbuild: false
  unrs-resolver: false
  vue-demi: false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.3
  vite-plus: 0.3.3
overrides:
  vite@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
